# EmailVerification Configuration File

Thanks for purchasing EmailVerification plugin and belive Hogo Studios since 2017.

Our motive is simplicity and efficiency, we hope the plugin will help your community!

ᴏꜰꜰɪᴄɪᴀʟ ʟɪɴᴋꜱ:
- https://hogostudios.com
- https://discord.gg/yq9gC87b58 

Plugin was created for our server so that we could have contact information from each player!​
​
It helped the server a lot because when you have contact with each player,​
you can only return the old players by e-mail if you are doing email marketing for your server​


this plugin was made in accordance with the law on collecting people's contact emails,
players agree upon signing up to the e-mail list that they want you to send them updates on your work

⚫ If you have any questions, we have full support on the Discord ⬋

➦ https://discord.gg/yq9gC87b58

(you can write a message in a #quick-support channel or open a private ticket in #support)

TOS:

By purchasing our services you have our license to use them and you can do whatever you want with them other than reselling them

Also, any sharing of purchased files with other people who have not previously purchased the service may lead to a lawsuit in accordance with copyright law


@ʜᴏɢᴏꜱᴛᴜᴅɪᴏꜱ

----------------------------------
For half a decade we have been developing custom plugins and scripts with implementation on
our server which is the most popular Minecraft server in Central Europe, with the experience
of us and our team and knowing what is missing from minecraft servers in general,
we have opened an agency that is available as Marketplace where everyone can obtain our services
and use them for themselves with constant support and security in the service.

We are the first team to implement WEB3 and blockchain technology on game servers and on Minecraft as a game

WEBSITE: https://hogostudios.com

our team includes all digital businesses from
graphic design, map design and builds to plugin programming


transparency is important, which is why this Discord server has been launched so that all customers have support and insight into what we are doing.


with each service purchased, you also receive updates of the same!
not even 1 plugin and service is outdated


MORE INFO:
Our Minecraft Server:
- Discord: https://discord.gg/xnbm68Et6x
- Site: https://hogrealms.com

# Message shown when a player typed verify command wrong
WrongVerifySyntax: "&cPlease use /verify <email>"

# Message shown when a player typed verify command while he/she is already verified 
AlreadyVerified: "&cYou've already added your email address to newsletter!"

# Message shown when a player joins the servers and is not yet verified
VerificationReminder: "&eSign up for newsletter and get a starter reward using: /verify <email>"

# When a player successfully verifies the email
# You can find a list of all sounds here: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
VerificationSuccess: 
  Personal: "&aYou have successfully added your email address!"
  Global: "%player%&a signed up for newsletter and received rewards!&8 (&7&n/verify email&8)"
  Sound: ENTITY_PLAYER_LEVELUP 
  Commands:
  - "give %player% diamond 1"
  
# Valid Email Endings
ValidEndings:
- "@gmail.com"
- "@yahoo.com"

# Message shown to player when they type an email address that does not end with one of the above items of the list
InvalidEmail: "&cInvalid email address!"
