#TimedItem configuration file

Thanks for purchasing EmailVerification plugin and belive Hogo Studios since 2017.

Our motive is simplicity and efficiency, we hope the plugin will help your community!

ᴏꜰꜰɪᴄɪᴀʟ ʟɪɴᴋꜱ:
- https://hogostudios.com
- https://discord.gg/yq9gC87b58

Plugin was created as private for our server to sustain the economy

we wanted to reward the players for things but not to have too many of those things in the world because then they would lose value.



⚫ If you have any questions, we have full support on the Discord ⬋

➦ https://discord.gg/yq9gC87b58

(you can write a message in a #quick-support channel or open a private ticket in #support)



TOS:

By purchasing our services you have our license to use them and you can do whatever you want with them other than reselling them

Also, any sharing of purchased files with other people who have not previously purchased the service may lead to a lawsuit in accordance with copyright law


@ʜᴏɢᴏꜱᴛᴜᴅɪᴏꜱ

----------------------------------
For half a decade we have been developing custom plugins and scripts with implementation on
our server which is the most popular Minecraft server in Central Europe, with the experience
of us and our team and knowing what is missing from game servers in general,
we have opened an agency that is available as Marketplace where everyone can obtain our services
and use them for themselves with constant support and security in the service.

We are the first team to implement WEB3 and blockchain technology on game servers and on Minecraft as a game

WEBSITE: https://hogostudios.com

our team consists of experts in the field of visual design,
graphic design, development and 3D modeling


transparency is important, which is why this Discord server has been launched so that all customers have support and insight into what we are doing.


with each service purchased, you also receive updates of the same!
not even 1 plugin and service is outdated


MORE INFO:
Our Minecraft Server:
- Discord: https://discord.gg/xnbm68Et6x
- Site: https://hogrealms.com

# TimeFormat of "/timeditem TimeFormat" command
# Please use all of the following list's shortcuts 
# (separate the first three from the last three with a space character, DO NOT use space character anywhere else):
# - yyyy = year
# - MM = month
# - dd = day
# - HH = hours
# - mm = minutes
# - ss = seconds
# e.g TimeFormat: "dd:MM:yyyy HH:mm:ss"
#     then the command is /timeditem dd:MM:yyyy HH:mm:ss
#     like /timeditem 01:01:2023 00:00:00
TimeFormat: "dd:MM:yyyy HH:mm:ss"

# Message shown when player uses timeditem command and does not hold any items
HoldItemMessage: "&cPlease hold an item to convert it to TimedItem!"

# %format% placeholder is taken from above TimeFormat
WrongSyntaxMessage: "&cPlease use: /timeditem %format%"

# How will the expiration date's prefix be displayed in item's lore
# The date will be displayed after the below prefix
DateLorePrefix: "&cExpires: "

# Message sent to player when an item expires
ExpirationMessage: "&eAn item from your inventory has expired!"

# Every how many minutes should the server check if an item is expired
# If expiration dates on most items are large time periods consider setting a big number for CheckTime to avoid unnecessary lag
CheckTime: 1
